name: 'Get Next Nuget Package Version from GitHub'
description: 'Action for getting Next Nuget Package Version from GitHub'
author: 'rexebin'

# Define your inputs here.
inputs:
  org:
    description: 'Organization name'
    required: true
  packageName:
    description: 'Package name'
    required: true
  publishBeta:
    description: 'Is beta version'
    required: false
    default: 'false'
  majorVersion:
    description: 'Major version'
    required: false
    default: '1'
  minorVersion:
    description: 'Minor version'
    required: false
    default: '0'

# Define your outputs here.
outputs:
  version:
    description: 'The version of the package'

runs:
  using: node20
  main: dist/index.js
